# Generated by Django 3.0.6 on 2020-05-09 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(max_length=32, verbose_name='组名字')),
                ('groupcreate_data', models.DateTimeField(auto_now_add=True, null=True, verbose_name='组创建时间')),
                ('groupupdate_data', models.DateTimeField(auto_now_add=True, null=True, verbose_name='组更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='host_idc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idcname', models.CharField(max_length=64, verbose_name='机房名字')),
                ('idcagent', models.CharField(max_length=64, verbose_name='机房代理商')),
                ('idcaddress', models.CharField(max_length=64, verbose_name='机房地址')),
            ],
        ),
        migrations.CreateModel(
            name='host_manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostuser', models.CharField(max_length=64, verbose_name='登录账户')),
                ('hostpasswd', models.CharField(max_length=64, verbose_name='登录密码')),
                ('hostport', models.IntegerField(verbose_name='主机端口')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('email', models.EmailField(max_length=32, verbose_name='邮箱')),
                ('gid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drfapi.group')),
            ],
        ),
        migrations.CreateModel(
            name='host_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hosttype', models.CharField(max_length=64, verbose_name='主机类型')),
                ('hostname', models.CharField(max_length=64, verbose_name='主机名')),
                ('hostip', models.GenericIPAddressField(db_index=True, protocol='ipv4', verbose_name='ip')),
                ('hostconfig', models.CharField(max_length=64, verbose_name='主机配置')),
                ('hostcreate_data', models.DateTimeField(auto_now_add=True, verbose_name='主机创建时间')),
                ('hostupdate_data', models.DateTimeField(auto_now_add=True, verbose_name='主机更新时间')),
                ('billing_idcid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drfapi.host_idc')),
                ('billing_managerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drfapi.host_manager')),
            ],
        ),
    ]
